version: '3.7'
services:

  traccar:
    deploy:
      restart_policy:
        condition: any 
        delay: 5s
        max_attempts: 3
        window: 120s      

  mysql:
    deploy:
      restart_policy:
        condition: any 
        delay: 5s
        max_attempts: 3
        window: 120s
